FROM docker:28.2.0-rc.1-dind-rootless
ENV TARGETARCH="linux-x64"
# Also can be "linux-arm", "linux-arm64".

RUN apk update && apk upgrade
RUN apk add --no-cache curl git jq icu-libs

RUN apk add --no-cache \
  bash \
  curl \
  jq \
  tar \
  coreutils \
  icu-libs \
  ca-certificates \
  su-exec \
  shadow


WORKDIR /azp/

COPY ./start.sh ./
RUN chmod +x ./start.sh

# Create agent user and set up home directory
RUN adduser -D -h /home/agent agent
#RUN chown -R agent:agent /azp /home/agent

USER agent
# Another option is to run the agent as root.
#ENV AGENT_ALLOW_RUNASROOT="true"

ENTRYPOINT [ "./start.sh" ]
